name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip PopByteHPPApp.zip
        run: |
          unzip -q PopByteHPPApp.zip -d src
          echo "APP_DIR=src" >> $GITHUB_ENV
          ls -la src

      # 🟡 Pasang Flutter dulu
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      # 🟢 Baru generate folder Android v2 embedding
      - name: Generate modern Android folder
        working-directory: ${{ env.APP_DIR }}
        run: |
          flutter create . --platforms=android --org com.popbyte --project-name popbyte_hpp_app --no-pub --overwrite

      - name: Get dependencies
        working-directory: ${{ env.APP_DIR }}
        run: flutter pub get

      - name: Build debug APK
        working-directory: ${{ env.APP_DIR }}
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PopByteHPP-debug-apk
          path: ${{ env.APP_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
